package agenda.db;

import agenda.db.Contacto;
import agenda.db.DBContactos;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUI extends javax.swing.JFrame {
    
    private final DBContactos dbContactos = new DBContactos();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        cargarContactosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnAgregar = new javax.swing.JButton();
        jTxtNombre = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jTxtEmpresa = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtCorreoElectronico = new javax.swing.JTextField();
        jLblNombre = new javax.swing.JLabel();
        jLblApellidos = new javax.swing.JLabel();
        jLblTelefono = new javax.swing.JLabel();
        jLblCorreoElectronico = new javax.swing.JLabel();
        jLblEmpresa = new javax.swing.JLabel();
        jBtnBuscar = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnBorrar = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda de Contactos");

        jPanelBackground.setBackground(new java.awt.Color(127, 135, 191));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agenda de Contactos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Empresa", "Telefono", "Correo Electronico"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnAgregar.setBackground(new java.awt.Color(38, 198, 218));
        jBtnAgregar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jTxtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApellidoActionPerformed(evt);
            }
        });

        jLblNombre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLblNombre.setText("Nombre:");

        jLblApellidos.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLblApellidos.setText("Apellidos:");

        jLblTelefono.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLblTelefono.setText("Telefono:");

        jLblCorreoElectronico.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLblCorreoElectronico.setText("Correo:");

        jLblEmpresa.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLblEmpresa.setText("Empresa:");

        jBtnBuscar.setBackground(new java.awt.Color(153, 153, 153));
        jBtnBuscar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jBtnEditar.setBackground(new java.awt.Color(0, 51, 102));
        jBtnEditar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEditar.setText("Editar");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jBtnBorrar.setBackground(new java.awt.Color(255, 0, 0));
        jBtnBorrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnBorrar.setText("Borrar");
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });

        jBtnLimpiar.setBackground(new java.awt.Color(255, 193, 159));
        jBtnLimpiar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addComponent(jLblNombre)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLblApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLblEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLblCorreoElectronico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jBtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                        .addGap(107, 107, 107)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 100, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblNombre)
                            .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblApellidos)
                            .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblEmpresa)
                            .addComponent(jTxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblTelefono)
                            .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblCorreoElectronico)
                            .addComponent(jTxtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jBtnAgregar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        borrarContacto();
        cargarContactosEnTabla();
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        editarContacto();
        cargarContactosEnTabla();
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        buscarContacto(evt);
    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jTxtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApellidoActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        agregarContacto(evt);
        cargarContactosEnTabla();
    }//GEN-LAST:event_jBtnAgregarActionPerformed

   private boolean validarTelefono(String telefono) {
        return telefono.matches("\\d{3}-\\d{3}-\\d{4}");
    }

    private boolean validarCorreoElectronico(String correo) {
        return correo.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
    }

    private boolean validarCampos(String nombre, String apellido, String empresa, String telefono, String correoElectronico) {
        return !nombre.trim().isEmpty() &&
               !apellido.trim().isEmpty() &&
               !empresa.trim().isEmpty() &&
               !telefono.trim().isEmpty() &&
               !correoElectronico.trim().isEmpty();
    }
        public void agregarContacto(ActionEvent e) {
        String nombre = jTxtNombre.getText();
        String apellido = jTxtApellido.getText();
        String empresa = jTxtEmpresa.getText();
        String telefono = jTxtTelefono.getText();
        String correoElectronico = jTxtCorreoElectronico.getText();
      
        if (validarCampos(nombre, apellido, empresa, telefono, correoElectronico)) {
            if (validarTelefono(telefono) && validarCorreoElectronico(correoElectronico)) {
                Contacto nuevoContacto = new Contacto(nombre, apellido, empresa, telefono, correoElectronico);

                try {
                    dbContactos.agregarContacto(nuevoContacto);
                    limpiarCampos();
                    JOptionPane.showMessageDialog(null, "Contacto agregado con Exito!");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(null, "Formato Incorrecto.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
        }
    }
    
    public void buscarContacto(ActionEvent evt) {
        String nombre = jTxtNombre.getText();
        
        if (!nombre.trim().isEmpty()) {
            Contacto contacto = dbContactos.buscarContacto(nombre);

            if (contacto != null) {
                jTxtApellido.setText(contacto.getApellido());
                jTxtEmpresa.setText(contacto.getEmpresa());
                jTxtTelefono.setText(contacto.getTelefono());
                jTxtCorreoElectronico.setText(contacto.getCorreoElectronico());
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron registros con el nombre proporcionado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese una nueva consulta.");
        }
    }
    
    public void editarContacto() {
        String nombre = jTxtNombre.getText();
        String apellido = jTxtApellido.getText();
        String empresa = jTxtEmpresa.getText();
        String telefono = jTxtTelefono.getText();
        String correoElectronico = jTxtCorreoElectronico.getText();

        if (validarCampos(nombre, apellido, empresa, telefono, correoElectronico)) {
            if (validarTelefono(telefono) && validarCorreoElectronico(correoElectronico)) {
                Contacto nuevoContacto = new Contacto(nombre, apellido, empresa, telefono, correoElectronico);

                dbContactos.editarContacto(nuevoContacto);
                JOptionPane.showMessageDialog(null, "Se actualizaron los datos del contacto.");
            } else {
                JOptionPane.showMessageDialog(null, "Formato Incorrecto.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
        }
    }
    
    public void borrarContacto() {
        String nombre = jTxtNombre.getText();

        if (!nombre.trim().isEmpty()) {
            dbContactos.borrarContacto(nombre);
            limpiarCampos();
            JOptionPane.showMessageDialog(null, "Contacto eliminado satisfactoriamente.");
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese una nueva consulta.");
        }
    }
    
    public void limpiarCampos() {
        jTxtNombre.setText("");
        jTxtApellido.setText("");
        jTxtEmpresa.setText("");
        jTxtTelefono.setText("");
        jTxtCorreoElectronico.setText("");
    }
    
    public void cargarContactosEnTabla() {
       List<Contacto> contactos = dbContactos.obtenerTodosLosContactos();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Empresa");
        modelo.addColumn("Telefono");
        modelo.addColumn("CorreoElectronico");

        for (Contacto contacto : contactos) {
            Object[] fila = {
                contacto.getId(),
                contacto.getNombre(),
                contacto.getApellido(),
                contacto.getEmpresa(),
                contacto.getTelefono(),
                contacto.getCorreoElectronico()
            };
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblApellidos;
    private javax.swing.JLabel jLblCorreoElectronico;
    private javax.swing.JLabel jLblEmpresa;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblTelefono;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtCorreoElectronico;
    private javax.swing.JTextField jTxtEmpresa;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtTelefono;
    // End of variables declaration//GEN-END:variables
}
